SDO_Exception::getCause -- 例外の原因を取得する

  mixed SDO_Exception::getCause()~

この関数は、 実験的 なものです。この関数の動作・
名前・その他ドキュメントに書かれている事項は、予告なく、将来的な
PHP のリリースにおいて変更される可能性があります。
この関数は自己責任で使用してください。

この例外の原因を返します。原因が存在しない場合や不明な場合には
NULL を返します。典型的な原因は SDO_CPPException
オブジェクトで、
追加の診断情報を取得するために使用されます。

なし。

この例外の原因を返します。原因が存在しない場合や不明な場合には
NULL を返します。

vim:ft=help:
